language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.0
script: bundle exec rspec spec
notifications:
  hipchat:
    rooms:
      secure: yBwhX5j87QTG4nKTkJ8j9pIETegsnu7CZL4Tjzas98+cu8WQa1Xafqhf8LZFLoDCwGI5R4N5LreSQM3tWY0nsu0gj+/Zl8/6PvvaJvwslxDSMtTxqe/+Hr+ndTytmKrI2qFZgliNPi9hbWoXVSfFw35H3RalDU9oqoG7l/xeTTQ=
